### ISSUE TITLE
Can't Install the package

### ISSUE THREAD

**Issue by raduskymariano** [robertmartin8/PyPortfolioOpt#100]
When I call pip install pyportfolioopt on anaconda powershell this keeps popping up

  ERROR: Failed building wheel for scs
  Running setup.py clean for scs
Failed to build cvxpy ecos scs
ERROR: Could not build wheels for cvxpy which use PEP 517 and cannot be installe
d directly
(base) PS C:\Users\Hp>

How can I fix this? Im kindda lost

**Comment by robertmartin8** [comment]
Hi @raduskymariano,

Could you let me know what version of python you're running? And it'd be good if you could check whether `pip install cvxpy` works :) 

Best,
Robert

**Comment by sakilli** [comment]
> When I call pip install pyportfolioopt on anaconda powershell this keeps popping up
> 
> ERROR: Failed building wheel for scs
> Running setup.py clean for scs
> Failed to build cvxpy ecos scs
> ERROR: Could not build wheels for cvxpy which use PEP 517 and cannot be installe
> d directly
> (base) PS C:\Users\Hp>
> 
> How can I fix this? Im kindda lost

I solved that issue on my friends windows PC by downloading C++.(I basically downloaded Visual Studio and in the installation chose C++)

**Comment by robertmartin8** [comment]
@sakilli 

Great! Is it working now?

**Comment by robertmartin8** [comment]
I'm closing for now. Please reopen if you're still having a problem!

**Comment by kalyaniyer9** [comment]
I am facing the same issue on Mac. Can someone please help me with the same?

**Comment by kalyaniyer9** [comment]
> Hi @raduskymariano,
> 
> Could you let me know what version of python you're running? And it'd be good if you could check whether `pip install cvxpy` works :)
> 
> Best,
> Robert

Could you please help me with the same for Mac? I tried running 'pip install cvxpy' I got the following error. 

Collecting cvxpy
  Using cached cvxpy-1.1.6.tar.gz (1.0 MB)
  Installing build dependencies ... error
  ERROR: Command errored out with exit status 1:
   command: /Users/kalyani/opt/anaconda3/bin/python /Users/kalyani/opt/anaconda3/lib/python3.8/site-packages/pip install --ignore-installed --no-user --prefix /private/var/folders/_t/dsckqzks0z55kqmpksgh1nc40000gn/T/pip-build-env-e0un6vii/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'numpy >= 1.15' 'scipy >= 1.1.0' 'setuptools>=40.8.0' wheel
       cwd: None
  Complete output (44 lines):
  Traceback (most recent call last):
    File "/Users/kalyani/opt/anaconda3/lib/python3.8/runpy.py", line 194, in _run_module_as_main
      return _run_code(code, main_globals, None,
    File "/Users/kalyani/opt/anaconda3/lib/python3.8/runpy.py", line 87, in _run_code
      exec(code, run_globals)
    File "/Users/kalyani/opt/anaconda3/lib/python3.8/site-packages/pip/__main__.py", line 26, in <module>
      sys.exit(_main())
    File "/Users/kalyani/opt/anaconda3/lib/python3.8/site-packages/pip/_internal/cli/main.py", line 73, in main
      command = create_command(cmd_name, isolated=("--isolated" in cmd_args))
    File "/Users/kalyani/opt/anaconda3/lib/python3.8/site-packages/pip/_internal/commands/__init__.py", line 104, in create_command
      module = importlib.import_module(module_path)
    File "/Users/kalyani/opt/anaconda3/lib/python3.8/importlib/__init__.py", line 127, in import_module
      return _bootstrap._gcd_import(name[level:], package, level)
    File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
    File "<frozen importlib._bootstrap>", line 991, in _find_and_load
    File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
    File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
    File "<frozen importlib._bootstrap_external>", line 783, in exec_module
    File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
    File "/Users/kalyani/opt/anaconda3/lib/python3.8/site-packages/pip/_internal/commands/install.py", line 24, in <module>
      from pip._internal.cli.req_command import RequirementCommand, with_cleanup
    File "/Users/kalyani/opt/anaconda3/lib/python3.8/site-packages/pip/_internal/cli/req_command.py", line 16, in <module>
      from pip._internal.index.package_finder import PackageFinder
    File "/Users/kalyani/opt/anaconda3/lib/python3.8/site-packages/pip/_internal/index/package_finder.py", line 21, in <module>
      from pip._internal.index.collector import parse_links
    File "/Users/kalyani/opt/anaconda3/lib/python3.8/site-packages/pip/_internal/index/collector.py", line 14, in <module>
      from pip._vendor import html5lib, requests
    File "/Users/kalyani/opt/anaconda3/lib/python3.8/site-packages/pip/_vendor/requests/__init__.py", line 114, in <module>
      from . import utils
    File "/Users/kalyani/opt/anaconda3/lib/python3.8/site-packages/pip/_vendor/requests/utils.py", line 25, in <module>
      from . import certs
    File "/Users/kalyani/opt/anaconda3/lib/python3.8/site-packages/pip/_vendor/requests/certs.py", line 15, in <module>
      from pip._vendor.certifi import where
    File "/Users/kalyani/opt/anaconda3/lib/python3.8/site-packages/pip/_vendor/certifi/__init__.py", line 1, in <module>
      from .core import contents, where
    File "/Users/kalyani/opt/anaconda3/lib/python3.8/site-packages/pip/_vendor/certifi/core.py", line 12, in <module>
      from importlib.resources import read_text
    File "/Users/kalyani/opt/anaconda3/lib/python3.8/importlib/resources.py", line 11, in <module>
      from typing import Iterable, Iterator, Optional, Set, Union   # noqa: F401
    File "/Users/kalyani/opt/anaconda3/lib/python3.8/site-packages/typing.py", line 1359, in <module>
      class Callable(extra=collections_abc.Callable, metaclass=CallableMeta):
    File "/Users/kalyani/opt/anaconda3/lib/python3.8/site-packages/typing.py", line 1007, in __new__
      self._abc_registry = extra._abc_registry
  AttributeError: type object 'Callable' has no attribute '_abc_registry'
  ----------------------------------------
ERROR: Command errored out with exit status 1: /Users/kalyani/opt/anaconda3/bin/python /Users/kalyani/opt/anaconda3/lib/python3.8/site-packages/pip install --ignore-installed --no-user --prefix /private/var/folders/_t/dsckqzks0z55kqmpksgh1nc40000gn/T/pip-build-env-e0un6vii/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'numpy >= 1.15' 'scipy >= 1.1.0' 'setuptools>=40.8.0' wheel Check the logs for full command output.
Note: you may need to restart the kernel to use updated packages.

**Comment by Carolinabtt** [comment]
I got the same error. here is the link with the instructions to use PyPortfolioOpt, and it contains the link to download Visual Studio for windows 10.
https://pypi.org/project/pyportfolioopt/
I installed and new it works.
Hope it help

**Comment by robertmartin8** [comment]
@kalyaniyer9 

Could you check if you've installed developer tools (instructions [here](https://osxdaily.com/2014/02/12/install-command-line-tools-mac-os-x/))? After that, you need to download C++ (see [here](https://github.com/robertmartin8/PyPortfolioOpt/issues/181)).

**Comment by kalyaniyer9** [comment]
Thank you for your email. I used Google Collaboratory for running the
package and it worked flawlessly.

**Comment by AtkinsonT** [comment]
HI Robert, i'm getting this issue. Have tried a lot of different routes but nothing is helping.
Tom

**Comment by 88d52bdba0366127fffca9dfa93895** [comment]
@AtkinsonT please provide more information about your environment. Maybe you could you check if you've installed developer tools (instructions [here](https://osxdaily.com/2014/02/12/install-command-line-tools-mac-os-x/))? After that, you need to download C++ (see https://github.com/robertmartin8/PyPortfolioOpt/issues/181). This issue relate to the CVXPY installation.

**Comment by AtkinsonT** [comment]
HI, Windows 10. Python 3.12.2. USing Cmd, but have also tried poetry.
Have installed developer tools and C++

**Comment by AtkinsonT** [comment]
Whole error message is below. cmake is installed


  error: subprocess-exited-with-error

  × Building wheel for qdldl (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [66 lines of output]
      running bdist_wheel
      running build
      running build_ext
      Traceback (most recent call last):
        File "<frozen runpy>", line 198, in _run_module_as_main
        File "<frozen runpy>", line 88, in _run_code
        File "C:\Users\Tomos Atkinson\AppData\Local\Programs\Python\Python312\Scripts\cmake.exe\__main__.py", line 4, in <module>
      ModuleNotFoundError: No module named 'cmake'
      Traceback (most recent call last):
        File "C:\Users\Tomos Atkinson\AppData\Local\Programs\Python\Python312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Users\Tomos Atkinson\AppData\Local\Programs\Python\Python312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\Tomos Atkinson\AppData\Local\Programs\Python\Python312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 251, in build_wheel
          return _build_backend().build_wheel(wheel_directory, config_settings,
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\Tomos Atkinson\AppData\Local\Temp\pip-build-env-g01bvqf6\overlay\Lib\site-packages\setuptools\build_meta.py", line 410, in build_wheel
          return self._build_with_temp_dir(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\Tomos Atkinson\AppData\Local\Temp\pip-build-env-g01bvqf6\overlay\Lib\site-packages\setuptools\build_meta.py", line 395, in _build_with_temp_dir
          self.run_setup()
        File "C:\Users\Tomos Atkinson\AppData\Local\Temp\pip-build-env-g01bvqf6\overlay\Lib\site-packages\setuptools\build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 113, in <module>
        File "C:\Users\Tomos Atkinson\AppData\Local\Temp\pip-build-env-g01bvqf6\overlay\Lib\site-packages\setuptools\__init__.py", line 103, in setup
          return distutils.core.setup(**attrs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\Tomos Atkinson\AppData\Local\Temp\pip-build-env-g01bvqf6\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 185, in setup
          return run_commands(dist)
                 ^^^^^^^^^^^^^^^^^^
        File "C:\Users\Tomos Atkinson\AppData\Local\Temp\pip-build-env-g01bvqf6\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 201, in run_commands
          dist.run_commands()
        File "C:\Users\Tomos Atkinson\AppData\Local\Temp\pip-build-env-g01bvqf6\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "C:\Users\Tomos Atkinson\AppData\Local\Temp\pip-build-env-g01bvqf6\overlay\Lib\site-packages\setuptools\dist.py", line 963, in run_command
          super().run_command(command)
        File "C:\Users\Tomos Atkinson\AppData\Local\Temp\pip-build-env-g01bvqf6\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "C:\Users\Tomos Atkinson\AppData\Local\Temp\pip-build-env-g01bvqf6\normal\Lib\site-packages\wheel\bdist_wheel.py", line 368, in run
          self.run_command("build")
        File "C:\Users\Tomos Atkinson\AppData\Local\Temp\pip-build-env-g01bvqf6\overlay\Lib\site-packages\setuptools\_distutils\cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "C:\Users\Tomos Atkinson\AppData\Local\Temp\pip-build-env-g01bvqf6\overlay\Lib\site-packages\setuptools\dist.py", line 963, in run_command
          super().run_command(command)
        File "C:\Users\Tomos Atkinson\AppData\Local\Temp\pip-build-env-g01bvqf6\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "C:\Users\Tomos Atkinson\AppData\Local\Temp\pip-build-env-g01bvqf6\overlay\Lib\site-packages\setuptools\_distutils\command\build.py", line 131, in run
          self.run_command(cmd_name)
        File "C:\Users\Tomos Atkinson\AppData\Local\Temp\pip-build-env-g01bvqf6\overlay\Lib\site-packages\setuptools\_distutils\cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "C:\Users\Tomos Atkinson\AppData\Local\Temp\pip-build-env-g01bvqf6\overlay\Lib\site-packages\setuptools\dist.py", line 963, in run_command
          super().run_command(command)
        File "C:\Users\Tomos Atkinson\AppData\Local\Temp\pip-build-env-g01bvqf6\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "C:\Users\Tomos Atkinson\AppData\Local\Temp\pip-build-env-g01bvqf6\overlay\Lib\site-packages\setuptools\command\build_ext.py", line 89, in run
          _build_ext.run(self)
        File "C:\Users\Tomos Atkinson\AppData\Local\Temp\pip-build-env-g01bvqf6\overlay\Lib\site-packages\setuptools\_distutils\command\build_ext.py", line 345, in run
          self.build_extensions()
        File "<string>", line 81, in build_extensions
        File "C:\Users\Tomos Atkinson\AppData\Local\Programs\Python\Python312\Lib\subprocess.py", line 466, in check_output
          return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\Tomos Atkinson\AppData\Local\Programs\Python\Python312\Lib\subprocess.py", line 571, in run
          raise CalledProcessError(retcode, process.args,
      subprocess.CalledProcessError: Command '['cmake', '--version']' returned non-zero exit status 1.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for qdldl
Failed to build qdldl
ERROR: Could not build wheels for qdldl, which is required to install pyproject.toml-based projects
