### ISSUE TITLE
Could not install on Anaconda (Python 3.8, Windows) using Poetry

### ISSUE THREAD

**Issue by sarvotham** [robertmartin8/PyPortfolioOpt#180]
When installing with poetry i get an AssertionError. Any way to fix this? I'm unable to install with pip either (raised another issue for this).

```
>>poetry add PyPortfolioOpt -v
Using virtualenv: C:\Users\foo\AppData\Local\pypoetry\Cache\virtualenvs\pyportfolioopt-2mwhmmbw-py3.8
Using version ^1.2.4 for PyPortfolioOpt

Updating dependencies
Resolving dependencies...

[AssertionError]


Traceback (most recent call last):
  File "C:\Users\foo\.poetry\lib\poetry\_vendor\py3.8\clikit\console_application.py", line 131, in run
    status_code = command.handle(parsed_args, io)
  File "C:\Users\foo\.poetry\lib\poetry\_vendor\py3.8\clikit\api\command\command.py", line 120, in handle
    status_code = self._do_handle(args, io)
  File "C:\Users\foo\.poetry\lib\poetry\_vendor\py3.8\clikit\api\command\command.py", line 171, in _do_handle
    return getattr(handler, handler_method)(args, io, self)
  File "C:\Users\foo\.poetry\lib\poetry\_vendor\py3.8\cleo\commands\command.py", line 92, in wrap_handle
    return self.handle()
  File "C:\Users\foo\.poetry\lib\poetry\console\commands\add.py", line 156, in handle
    status = installer.run()
  File "C:\Users\foo\.poetry\lib\poetry\installation\installer.py", line 74, in run
    self._do_install(local_repo)
  File "C:\Users\foo\.poetry\lib\poetry\installation\installer.py", line 161, in _do_install
    ops = solver.solve(use_latest=self._whitelist)
  File "C:\Users\foo\.poetry\lib\poetry\puzzle\solver.py", line 36, in solve
    packages, depths = self._solve(use_latest=use_latest)
  File "C:\Users\foo\.poetry\lib\poetry\puzzle\solver.py", line 180, in _solve
    result = resolve_version(
  File "C:\Users\foo\.poetry\lib\poetry\mixology\__init__.py", line 7, in resolve_version
    return solver.solve()
  File "C:\Users\foo\.poetry\lib\poetry\mixology\version_solver.py", line 80, in solve
    next = self._choose_package_version()
  File "C:\Users\foo\.poetry\lib\poetry\mixology\version_solver.py", line 391, in _choose_package_version
    for incompatibility in self._provider.incompatibilities_for(version):
  File "C:\Users\foo\.poetry\lib\poetry\puzzle\provider.py", line 561, in incompatibilities_for
    return [
  File "C:\Users\foo\.poetry\lib\poetry\puzzle\provider.py", line 562, in <listcomp>
    Incompatibility(
  File "C:\Users\foo\.poetry\lib\poetry\mixology\incompatibility.py", line 60, in __init__
    assert by_ref[ref] is not None
'''
```

**Comment by robertmartin8** [comment]
Hi @sarvotham,

Thanks for raising this, I haven't seen an issue like this before. What is the name of the poetry virtualenv that you are trying to install this into? Apparently some people have had problems when the name is the same as the package.

Cheers,
Robert

**Comment by sarvotham** [comment]
This was the one that was created: pyportfolioopt-2mwhmmbw-py3.8
