### ISSUE TITLE
Could not install on Windows Anaconda 

### ISSUE THREAD

**Issue by gunavanthmahendra** [robertmartin8/PyPortfolioOpt#230]
**Operating system, environment, python version**
Windows 10, anaconda, python3.8.5

**What you tried**
pip install pyportfolioopt

**Error message**
ERROR: Command errored out with exit status 1: 'C:\Users\guna3\anaconda3\python.exe' 'C:\Users\guna3\anaconda3\lib\site-packages\pip\_vendor\pep517\_in_process.py' prepare_metadata_for_build_wheel 'C:\Users\guna3\AppData\Local\Temp\tmptl_ro7gy' Check the logs for full command output.
Copy paste the terminal message here
```
   Preparing wheel metadata ... - ** On entry to DGEBAL parameter number  3 had an illegal value
 ** On entry to DGEHRD  parameter number  2 had an illegal value
 ** On entry to DORGHR DORGQR parameter number  2 had an illegal value
 ** On entry to DHSEQR parameter number  4 had an illegal value
error
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\guna3\anaconda3\python.exe' 'C:\Users\guna3\anaconda3\lib\site-packages\pip\_vendor\pep517\_in_process.py' prepare_metadata_for_build_wheel 'C:\Users\guna3\AppData\Local\Temp\tmptl_ro7gy'
         cwd: C:\Users\guna3\AppData\Local\Temp\pip-install-0h6jf_hf\cvxpy
    Complete output (55 lines):
    running dist_info
    creating C:\Users\guna3\AppData\Local\Temp\pip-modern-metadata-b15pkg6e\cvxpy.egg-info
    writing C:\Users\guna3\AppData\Local\Temp\pip-modern-metadata-b15pkg6e\cvxpy.egg-info\PKG-INFO
    writing dependency_links to C:\Users\guna3\AppData\Local\Temp\pip-modern-metadata-b15pkg6e\cvxpy.egg-info\dependency_links.txt
    writing requirements to C:\Users\guna3\AppData\Local\Temp\pip-modern-metadata-b15pkg6e\cvxpy.egg-info\requires.txt
    writing top-level names to C:\Users\guna3\AppData\Local\Temp\pip-modern-metadata-b15pkg6e\cvxpy.egg-info\top_level.txt
    writing manifest file 'C:\Users\guna3\AppData\Local\Temp\pip-modern-metadata-b15pkg6e\cvxpy.egg-info\SOURCES.txt'
    Traceback (most recent call last):
      File "C:\Users\guna3\anaconda3\lib\site-packages\pip\_vendor\pep517\_in_process.py", line 280, in <module>
        main()
      File "C:\Users\guna3\anaconda3\lib\site-packages\pip\_vendor\pep517\_in_process.py", line 263, in main
        json_out['return_val'] = hook(**hook_input['kwargs'])
      File "C:\Users\guna3\anaconda3\lib\site-packages\pip\_vendor\pep517\_in_process.py", line 133, in prepare_metadata_for_build_wheel
        return hook(metadata_directory, config_settings)
      File "C:\Users\guna3\AppData\Local\Temp\pip-build-env-axm357oe\overlay\Lib\site-packages\setuptools\build_meta.py", line 161, in prepare_metadata_for_build_wheel
        self.run_setup()
      File "C:\Users\guna3\AppData\Local\Temp\pip-build-env-axm357oe\overlay\Lib\site-packages\setuptools\build_meta.py", line 253, in run_setup
        super(_BuildMetaLegacyBackend,
      File "C:\Users\guna3\AppData\Local\Temp\pip-build-env-axm357oe\overlay\Lib\site-packages\setuptools\build_meta.py", line 145, in run_setup
        exec(compile(code, __file__, 'exec'), locals())
      File "setup.py", line 57, in <module>
        setup(
      File "C:\Users\guna3\AppData\Local\Temp\pip-build-env-axm357oe\overlay\Lib\site-packages\setuptools\__init__.py", line 153, in setup
        return distutils.core.setup(**attrs)
      File "C:\Users\guna3\anaconda3\lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "C:\Users\guna3\anaconda3\lib\distutils\dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "C:\Users\guna3\anaconda3\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "C:\Users\guna3\AppData\Local\Temp\pip-build-env-axm357oe\overlay\Lib\site-packages\setuptools\command\dist_info.py", line 31, in run
        egg_info.run()
      File "C:\Users\guna3\AppData\Local\Temp\pip-build-env-axm357oe\overlay\Lib\site-packages\setuptools\command\egg_info.py", line 298, in run
        self.find_sources()
      File "C:\Users\guna3\AppData\Local\Temp\pip-build-env-axm357oe\overlay\Lib\site-packages\setuptools\command\egg_info.py", line 305, in find_sources
        mm.run()
      File "C:\Users\guna3\AppData\Local\Temp\pip-build-env-axm357oe\overlay\Lib\site-packages\setuptools\command\egg_info.py", line 536, in run
        self.add_defaults()
      File "C:\Users\guna3\AppData\Local\Temp\pip-build-env-axm357oe\overlay\Lib\site-packages\setuptools\command\egg_info.py", line 572, in add_defaults
        sdist.add_defaults(self)
      File "C:\Users\guna3\anaconda3\lib\distutils\command\sdist.py", line 228, in add_defaults
        self._add_defaults_ext()
      File "C:\Users\guna3\anaconda3\lib\distutils\command\sdist.py", line 311, in _add_defaults_ext
        build_ext = self.get_finalized_command('build_ext')
      File "C:\Users\guna3\anaconda3\lib\distutils\cmd.py", line 299, in get_finalized_command
        cmd_obj.ensure_finalized()
      File "C:\Users\guna3\anaconda3\lib\distutils\cmd.py", line 107, in ensure_finalized
        self.finalize_options()
      File "setup.py", line 23, in finalize_options
        import numpy
      File "C:\Users\guna3\AppData\Local\Temp\pip-build-env-axm357oe\overlay\Lib\site-packages\numpy\__init__.py", line 305, in <module>
        _win_os_check()
      File "C:\Users\guna3\AppData\Local\Temp\pip-build-env-axm357oe\overlay\Lib\site-packages\numpy\__init__.py", line 302, in _win_os_check
        raise RuntimeError(msg.format(__file__)) from None
    RuntimeError: The current Numpy installation ('C:\\Users\\guna3\\AppData\\Local\\Temp\\pip-build-env-axm357oe\\overlay\\Lib\\site-packages\\numpy\\__init__.py') fails to pass a sanity check due to a bug in the windows runtime. See this issue for more information: https://tinyurl.com/y3dm3h86
![2020-11-25](https://user-images.githubusercontent.com/73594582/100315245-588fdb00-2fde-11eb-88a0-817521b72ad3.png)

**Comment by bvrilliance** [comment]
Do you have C++ installed?

**Comment by gunavanthmahendra** [comment]
Yes I have C++ installed I followed the instructions correctly

**Comment by x829901** [comment]
> I have the same problem. I installed Visual Studio Build Tool 2019 correctly I believe. I have uploaded a screenshot. 
> 
> (env4) C:\Users\25del\Python Projects>pip install PyPortfolioOpt
> Collecting PyPortfolioOpt
>   Using cached PyPortfolioOpt-1.2.7-py3-none-any.whl (48 kB)
> Collecting scipy<2.0,>=1.3
>   Using cached scipy-1.5.4-cp38-cp38-win_amd64.whl (31.4 MB)
> Collecting cvxpy<2.0,>=1.0
>   Using cached cvxpy-1.1.7.tar.gz (1.0 MB)
>   Installing build dependencies ... done
>   Getting requirements to build wheel ... done
>     Preparing wheel metadata ... \ ** On entry to DGEBAL parameter number  3 had an illegal value
>  ** On entry to DGEHRD  parameter number  2 had an illegal value
>  ** On entry to DORGHR DORGQR parameter number  2 had an illegal value
>  ** On entry to DHSEQR parameter number  4 had an illegal value
> error
>     ERROR: Command errored out with exit status 1:
>      command: 'C:\Users\25del\Anaconda3\envs\env4\python.exe' 'C:\Users\25del\Anaconda3\envs\env4\lib\site-packages\pip\_vendor\pep517\_in_process.py' prepare_metadata_for_build_wheel 'C:\Users\25del\AppData\Local\Temp\tmpv3atyfpr'
>          cwd: C:\Users\25del\AppData\Local\Temp\pip-install-t9xw9m8w\cvxpy
>     Complete output (55 lines):
>     running dist_info
>     creating C:\Users\25del\AppData\Local\Temp\pip-modern-metadata-nekw02hr\cvxpy.egg-info
>     writing C:\Users\25del\AppData\Local\Temp\pip-modern-metadata-nekw02hr\cvxpy.egg-info\PKG-INFO
>     writing dependency_links to C:\Users\25del\AppData\Local\Temp\pip-modern-metadata-nekw02hr\cvxpy.egg-info\dependency_links.txt
>     writing requirements to C:\Users\25del\AppData\Local\Temp\pip-modern-metadata-nekw02hr\cvxpy.egg-info\requires.txt
>     writing top-level names to C:\Users\25del\AppData\Local\Temp\pip-modern-metadata-nekw02hr\cvxpy.egg-info\top_level.txt
>     writing manifest file 'C:\Users\25del\AppData\Local\Temp\pip-modern-metadata-nekw02hr\cvxpy.egg-info\SOURCES.txt'
>     Traceback (most recent call last):
>       File "C:\Users\25del\Anaconda3\envs\env4\lib\site-packages\pip\_vendor\pep517\_in_process.py", line 280, in <module>
>         main()
>       File "C:\Users\25del\Anaconda3\envs\env4\lib\site-packages\pip\_vendor\pep517\_in_process.py", line 263, in main
>         json_out['return_val'] = hook(**hook_input['kwargs'])
>       File "C:\Users\25del\Anaconda3\envs\env4\lib\site-packages\pip\_vendor\pep517\_in_process.py", line 133, in prepare_metadata_for_build_wheel
>         return hook(metadata_directory, config_settings)
>       File "C:\Users\25del\AppData\Local\Temp\pip-build-env-gm7m10wb\overlay\Lib\site-packages\setuptools\build_meta.py", line 161, in prepare_metadata_for_build_wheel
>         self.run_setup()
>       File "C:\Users\25del\AppData\Local\Temp\pip-build-env-gm7m10wb\overlay\Lib\site-packages\setuptools\build_meta.py", line 253, in run_setup
>         super(_BuildMetaLegacyBackend,
>       File "C:\Users\25del\AppData\Local\Temp\pip-build-env-gm7m10wb\overlay\Lib\site-packages\setuptools\build_meta.py", line 145, in run_setup
>         exec(compile(code, __file__, 'exec'), locals())
>       File "setup.py", line 57, in <module>
>         setup(
>       File "C:\Users\25del\AppData\Local\Temp\pip-build-env-gm7m10wb\overlay\Lib\site-packages\setuptools\__init__.py", line 153, in setup
>         return distutils.core.setup(**attrs)
>       File "C:\Users\25del\Anaconda3\envs\env4\lib\distutils\core.py", line 148, in setup
>         dist.run_commands()
>       File "C:\Users\25del\Anaconda3\envs\env4\lib\distutils\dist.py", line 966, in run_commands
>         self.run_command(cmd)
>       File "C:\Users\25del\Anaconda3\envs\env4\lib\distutils\dist.py", line 985, in run_command
>         cmd_obj.run()
>       File "C:\Users\25del\AppData\Local\Temp\pip-build-env-gm7m10wb\overlay\Lib\site-packages\setuptools\command\dist_info.py", line 31, in run
>         egg_info.run()
>       File "C:\Users\25del\AppData\Local\Temp\pip-build-env-gm7m10wb\overlay\Lib\site-packages\setuptools\command\egg_info.py", line 298, in run
>         self.find_sources()
>       File "C:\Users\25del\AppData\Local\Temp\pip-build-env-gm7m10wb\overlay\Lib\site-packages\setuptools\command\egg_info.py", line 305, in find_sources
>         mm.run()
>       File "C:\Users\25del\AppData\Local\Temp\pip-build-env-gm7m10wb\overlay\Lib\site-packages\setuptools\command\egg_info.py", line 536, in run
>         self.add_defaults()
>       File "C:\Users\25del\AppData\Local\Temp\pip-build-env-gm7m10wb\overlay\Lib\site-packages\setuptools\command\egg_info.py", line 572, in add_defaults
>         sdist.add_defaults(self)
>       File "C:\Users\25del\Anaconda3\envs\env4\lib\distutils\command\sdist.py", line 228, in add_defaults
>         self._add_defaults_ext()
>       File "C:\Users\25del\Anaconda3\envs\env4\lib\distutils\command\sdist.py", line 311, in _add_defaults_ext
>         build_ext = self.get_finalized_command('build_ext')
>       File "C:\Users\25del\Anaconda3\envs\env4\lib\distutils\cmd.py", line 299, in get_finalized_command
>         cmd_obj.ensure_finalized()
>       File "C:\Users\25del\Anaconda3\envs\env4\lib\distutils\cmd.py", line 107, in ensure_finalized
>         self.finalize_options()
>       File "setup.py", line 23, in finalize_options
>         import numpy
>       File "C:\Users\25del\AppData\Local\Temp\pip-build-env-gm7m10wb\overlay\Lib\site-packages\numpy\__init__.py", line 305, in <module>
>         _win_os_check()
>       File "C:\Users\25del\AppData\Local\Temp\pip-build-env-gm7m10wb\overlay\Lib\site-packages\numpy\__init__.py", line 302, in _win_os_check
>         raise RuntimeError(msg.format(__file__)) from None
>     RuntimeError: The current Numpy installation ('C:\\Users\\25del\\AppData\\Local\\Temp\\pip-build-env-gm7m10wb\\overlay\\Lib\\site-packages\\numpy\\__init__.py') fails to pass a sanity check due to a bug in the windows runtime. See this issue for more information: https://tinyurl.com/y3dm3h86
>     ----------------------------------------
> ERROR: Command errored out with exit status 1: 'C:\Users\25del\Anaconda3\envs\env4\python.exe' 'C:\Users\25del\Anaconda3\envs\env4\lib\site-packages\pip\_vendor\pep517\_in_process.py' prepare_metadata_for_build_wheel 'C:\Users\25del\AppData\Local\Temp\tmpv3atyfpr' Check the logs for full command output.

![image](https://user-images.githubusercontent.com/57601600/100534237-3f4f8000-31d2-11eb-921c-3ee56d2ff19d.png)

**Comment by x829901** [comment]
Could it be that there is a bug in the Visual Studio 2019 concerning numpy and scipy? Apparently, the workaround is to 

> pip uninstall numpy

 and 

> pip install numpy==1.19.3

https://developercommunity.visualstudio.com/content/problem/1207405/fmod-after-an-update-to-windows-2004-is-causing-a.html

However, after doing this, when I try to 

> pip install PyPortfolioOpt

To a new environment with Python 3.8.5, I get the same error as above. This started as soon as I switched to a new computer and tried to install all my usual packages to a new environment. This is a HUGE problem as I use this for work.

**Comment by x829901** [comment]
Duplicate of #223

This workaround solution worked for me. Created new environment with `conda create -n myenv python=3.6 numpy=1.19.3`. Hopefully Microsoft fixes the fmod bug soon.

**Comment by robertmartin8** [comment]
Sorry I can't be of assistance here as I'm on macOS. It sounds like some thorny issue related to C++ interacting with some python libraries. Glad you have a workaround!

**Comment by x829901** [comment]
Hello, I wanted to update everyone on my work dealing with this issue. Here is an update from Microsoft's developer team regarding their upcoming fix to one of their Windows updates breaking numpy==1.19.4 on python 3.8, thereby making PyPortfolioOpt impossible to `pip install PyPortfolioOpt` on python 3.8 on Windows 10. They estimate a fix coming out at the end of January but you can test the fix. Below I post the message from the Senior Software Engineer. [https://tinyurl.com/y3dm3h86](url).

```
Hey everyone,

An Insider Preview Windows build with the fix is now available. Build 20270 is now in the Dev Channel: https://blogs.windows.com/windows-insider/2020/12/03/announcing-windows-10-insider-preview-build-20270/. If you are affected by this issue and want to test against the fix that will come via Windows Update, you can use this build. This is an insider build with other changes included, of course, so it is not entirely representative of the version that will be serviced, but it can be used to test for specific cases where the bug used to reproduce.

We are still on schedule for servicing Windows build 19041 (the current release version) at the end of January 2021.

Thanks!

Steve Wishnousky
Senior Software Engineer - Visual C++ Libraries
stwish@microsoft.com
```

I've been using the current workaround python==3.6 with numpy==1.19.3 solution for a few weeks now and frankly, it's not satisfactory. Python 3.6 and compatible packages have bugs and issues that have since been resolved in subsequent updated versions Python 3.7 and currently Python 3.8 with compatible packages. I've found myself encountering these bugs and having to manually fix them by searching for solutions and having to edit code in various dependencies where I encounter these bugs. Everything was working great before Microsoft broke numpy, so all I can really do is wait for them to come out with the update and keep using an inferior version of Python and compatible dependencies.

**Comment by robertmartin8** [comment]
@x829901 Appreciate the analysis – will keep this issue open until resolved!

> until PyPortfolioOpt becomes compatible with python 3.7<= and numpy 1.19.3<=

Is there anything I can do on my end to fix this? In the `requirements.txt`, I have `numpy>=1.17` so in principle PyPortfolioOpt _should_ be compatible with `python 3.7<= numpy 1.19.3<=`?

**Comment by NabilChouaib** [comment]
Found a workaround. Instead of:

pip install PyPortfolioOpt

I installed dependencies manually the used:

**pip install --no-dependencies PyPortfolioOpt**

**Comment by yordan-bankov** [comment]
1. I had tried "pip install PyPortfolioOpt" and received error for "m.lib".
2. Then I made "pip install --no-dependencies PyPortfolioOpt" - successfully.
3. Executed "pip install cvxopt" that gave me error "pip's dependency resolver does not currently take into account all the packages that are installed..." - etc.
4. Executed "pip uninstall cvxopt" - successfully.
5. Executed "conda install -c conda-forge cvxopt" - successfully.
6. Executed "pip install PyPortfolioOpt" - result "Requirement already satisfied".

**Comment by robertmartin8** [comment]
@yordan-bankov just to clarify, is it working now?

**Comment by yordan-bankov** [comment]
Yes PyPortfolioOpt works, but:

RuntimeError: "module compiled against API version 0xe but this version of numpy is 0xd"

7. Executed "pip uninstall numpy" - successfully.
8. Executed "pip install numpy" - installed and reported "tensorflow 2.3.1 requires numpy<1.19.0,>=1.16.0, but you have numpy 1.20.1 which is incompatible"

So now functions from  PyPortfolioOpt are OK, but I assume if I try to use something from TensorFlow, it will not work.

This below is relevant for Windows / Anaconda only:
The Anaconda is an additional level of abstraction above Python. In this respect Anaconda provides a set of modules which are maintained by conda. For example, Anaconda for Windows have numpy 1.19.0 in the Anaconda modules list. To have working PyPortfolioOpt it is required to have numpy 1.20.1.  This numpy is not supported by Anaconda set of modules. The numpy 1.20.1 can be installed using pip, and this will make PyPortfolioOpt working. On the other hand, other modules will also need manual update using pip.

**Comment by StephenKwokChina** [comment]
dear all,  the problem is not from  PyPortfolioOpt, It's from installing the dependecy cvxpy, before installing cvxpy you need install numpy+mkl not numpy.
**Here is the solution:**
NumPy+mkl: https://www.lfd.uci.edu/~gohlke/pythonlibs/#numpy
SCIPY: https://www.lfd.uci.edu/~gohlke/pythonlibs/#scipy
CVXOPT: https://www.lfd.uci.edu/~gohlke/pythonlibs/#cvxopt
SCS: https://www.lfd.uci.edu/~gohlke/pythonlibs/#scs
ECOS: https://www.lfd.uci.edu/~gohlke/pythonlibs/#ecos
OSQP: https://www.lfd.uci.edu/~gohlke/pythonlibs/#osqp
CVXcanon: https://www.lfd.uci.edu/~gohlke/pythonlibs/#cvxcanon
Fastcache: https://www.lfd.uci.edu/~gohlke/pythonlibs/#fastcache
Multiprocess: https://www.lfd.uci.edu/~gohlke/pythonlibs/#multiprocess
CVXPY：https://www.lfd.uci.edu/~gohlke/pythonlibs/#cvxpy
remember install the wheel one by one and **following the order please.**
