### ISSUE TITLE
Cannot install on Windows Python 3.8; something with NumPy?

### ISSUE THREAD

**Issue by RSKriegs** [robertmartin8/PyPortfolioOpt#236]
Hi, so I've got some bug while I was installing. The url shown in an error message leads me to C++ website, to the forum where the issue is discussed, however, the problem here is related to NumPy which is working fine for me. I have tried uninstalling NumPy and installing previous versions but it didn't work in case of PyPortfolioOpt. Seems like there is some problem with C++ code which isn't fixed yet, have you got any ideas how to get over it?

**Operating system, environment, python version**
Windows, Python 3.8, using Anaconda but installing through command prompt

**What you tried**
pip install pyportfolioopt

**Error message**
 ERROR: Command errored out with exit status 1:
     command: 'C:\Users\rafal\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\python.exe' 'C:\Users\rafal\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\pip\_vendor\pep517\_in_process.py' prepare_metadata_for_build_wheel 'C:\Users\rafal\AppData\Local\Temp\tmpd1ibkb4f'
         cwd: C:\Users\rafal\AppData\Local\Temp\pip-install-trq3jk7h\cvxpy_7268dc83360d4dbeb4a0acbc74492cc8
    Complete output (55 lines):
    running dist_info
    creating C:\Users\rafal\AppData\Local\Temp\pip-modern-metadata-nxqz_m9k\cvxpy.egg-info
    writing C:\Users\rafal\AppData\Local\Temp\pip-modern-metadata-nxqz_m9k\cvxpy.egg-info\PKG-INFO
    writing dependency_links to C:\Users\rafal\AppData\Local\Temp\pip-modern-metadata-nxqz_m9k\cvxpy.egg-info\dependency_links.txt
    writing requirements to C:\Users\rafal\AppData\Local\Temp\pip-modern-metadata-nxqz_m9k\cvxpy.egg-info\requires.txt
    writing top-level names to C:\Users\rafal\AppData\Local\Temp\pip-modern-metadata-nxqz_m9k\cvxpy.egg-info\top_level.txt
    writing manifest file 'C:\Users\rafal\AppData\Local\Temp\pip-modern-metadata-nxqz_m9k\cvxpy.egg-info\SOURCES.txt'
    Traceback (most recent call last):
      File "C:\Users\rafal\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\pip\_vendor\pep517\_in_process.py", line 280, in <module>
        main()
      File "C:\Users\rafal\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\pip\_vendor\pep517\_in_process.py", line 263, in main
        json_out['return_val'] = hook(**hook_input['kwargs'])
      File "C:\Users\rafal\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\pip\_vendor\pep517\_in_process.py", line 133, in prepare_metadata_for_build_wheel
        return hook(metadata_directory, config_settings)
      File "C:\Users\rafal\AppData\Local\Temp\pip-build-env-jhr6mupu\overlay\Lib\site-packages\setuptools\build_meta.py", line 161, in prepare_metadata_for_build_wheel
        self.run_setup()
      File "C:\Users\rafal\AppData\Local\Temp\pip-build-env-jhr6mupu\overlay\Lib\site-packages\setuptools\build_meta.py", line 253, in run_setup
        super(_BuildMetaLegacyBackend,
      File "C:\Users\rafal\AppData\Local\Temp\pip-build-env-jhr6mupu\overlay\Lib\site-packages\setuptools\build_meta.py", line 145, in run_setup
        exec(compile(code, __file__, 'exec'), locals())
      File "setup.py", line 57, in <module>
        setup(
      File "C:\Users\rafal\AppData\Local\Temp\pip-build-env-jhr6mupu\overlay\Lib\site-packages\setuptools\__init__.py", line 153, in setup
        return distutils.core.setup(**attrs)
      File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1776.0_x64__qbz5n2kfra8p0\lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1776.0_x64__qbz5n2kfra8p0\lib\distutils\dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1776.0_x64__qbz5n2kfra8p0\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "C:\Users\rafal\AppData\Local\Temp\pip-build-env-jhr6mupu\overlay\Lib\site-packages\setuptools\command\dist_info.py", line 31, in run
        egg_info.run()
      File "C:\Users\rafal\AppData\Local\Temp\pip-build-env-jhr6mupu\overlay\Lib\site-packages\setuptools\command\egg_info.py", line 298, in run
        self.find_sources()
      File "C:\Users\rafal\AppData\Local\Temp\pip-build-env-jhr6mupu\overlay\Lib\site-packages\setuptools\command\egg_info.py", line 305, in find_sources
        mm.run()
      File "C:\Users\rafal\AppData\Local\Temp\pip-build-env-jhr6mupu\overlay\Lib\site-packages\setuptools\command\egg_info.py", line 536, in run
        self.add_defaults()
      File "C:\Users\rafal\AppData\Local\Temp\pip-build-env-jhr6mupu\overlay\Lib\site-packages\setuptools\command\egg_info.py", line 572, in add_defaults
        sdist.add_defaults(self)
      File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1776.0_x64__qbz5n2kfra8p0\lib\distutils\command\sdist.py", line 228, in add_defaults
        self._add_defaults_ext()
      File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1776.0_x64__qbz5n2kfra8p0\lib\distutils\command\sdist.py", line 311, in _add_defaults_ext
        build_ext = self.get_finalized_command('build_ext')
      File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1776.0_x64__qbz5n2kfra8p0\lib\distutils\cmd.py", line 299, in get_finalized_command
        cmd_obj.ensure_finalized()
      File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1776.0_x64__qbz5n2kfra8p0\lib\distutils\cmd.py", line 107, in ensure_finalized
        self.finalize_options()
      File "setup.py", line 23, in finalize_options
        import numpy
      File "C:\Users\rafal\AppData\Local\Temp\pip-build-env-jhr6mupu\overlay\Lib\site-packages\numpy\__init__.py", line 305, in <module>
        _win_os_check()
      File "C:\Users\rafal\AppData\Local\Temp\pip-build-env-jhr6mupu\overlay\Lib\site-packages\numpy\__init__.py", line 302, in _win_os_check
        raise RuntimeError(msg.format(__file__)) from None
    RuntimeError: The current Numpy installation ('C:\\Users\\rafal\\AppData\\Local\\Temp\\pip-build-env-jhr6mupu\\overlay\\Lib\\site-packages\\numpy\\__init__.py') fails to pass a sanity check due to a bug in the windows runtime. See this issue for more information: https://tinyurl.com/y3dm3h86
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'C:\Users\rafal\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\python.exe' 'C:\Users\rafal\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\pip\_vendor\pep517\_in_process.py' prepare_metadata_for_build_wheel 'C:\Users\rafal\AppData\Local\Temp\tmpd1ibkb4f' Check the logs for full command output.

**Comment by robertmartin8** [comment]
Hi @RSKriegs,

Thanks for raising this. Unfortunately I'm on macOS so won't be of much use. However, this issue looks similar to #230 so maybe that will help you?

Best,
Robert

**Comment by robertmartin8** [comment]
@RSKriegs I'm closing this because it seems to be the same as #230 – please follow up in that thread if needed
