### ISSUE TITLE
Not able to upgrade to version 1.4 on windows

### ISSUE THREAD

**Issue by sabirjana** [robertmartin8/PyPortfolioOpt#281]
**Operating system, environment, python version**
Windows, anaconda, python3.8

**What you tried**
I have an existing version pyportfolioopt '1.2.7' and trying to update to the latest version - 1.4 using
pip install pyportfolioopt==1.4.0
or 
pip install PyPortfolioOpt --upgrade
or
pip install PyPortfolioOpt --upgrade --user

Existing installation
cvxopt 1.2.5.post1
cvxpy '1.1.10'

**Error message**

```
(base) C:\Windows\system32>pip install PyPortfolioOpt==1.4.0
ERROR: Error initializing plugin EntryPoint(name='macOS', value='keyring.backends.macOS', group='keyring.backends').
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 171, in _merge_into_criterion
    crit = self.state.criteria[name]
KeyError: 'pyportfolioopt'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Roaming\Python\Python38\site-packages\keyring\backend.py", line 202, in _load_plugins
    init_func = ep.load()
  File "C:\ProgramData\Anaconda3\lib\importlib\metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "C:\ProgramData\Anaconda3\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'keyring.backends.macOS'
Collecting PyPortfolioOpt==1.4.0
  Using cached PyPortfolioOpt-1.4.0-py3-none-any.whl (52 kB)
Requirement already satisfied: scipy<2.0,>=1.3 in c:\programdata\anaconda3\lib\site-packages (from PyPortfolioOpt==1.4.0) (1.6.0)
Requirement already satisfied: pandas>=0.19 in c:\programdata\anaconda3\lib\site-packages (from PyPortfolioOpt==1.4.0) (1.2.1)
Requirement already satisfied: numpy<2.0,>=1.12 in c:\programdata\anaconda3\lib\site-packages (from PyPortfolioOpt==1.4.0) (1.20.1)
Requirement already satisfied: cvxpy<2.0.0,>=1.1.10 in c:\programdata\anaconda3\lib\site-packages (from PyPortfolioOpt==1.4.0) (1.1.10)
Collecting cvxopt!=1.2.5.post1,<2.0,>=1.2
  Using cached cvxopt-1.2.5.tar.gz (6.7 MB)
Requirement already satisfied: scs>=1.1.6 in c:\programdata\anaconda3\lib\site-packages (from cvxpy<2.0.0,>=1.1.10->PyPortfolioOpt==1.4.0) (2.1.2)
Requirement already satisfied: osqp>=0.4.1 in c:\programdata\anaconda3\lib\site-packages (from cvxpy<2.0.0,>=1.1.10->PyPortfolioOpt==1.4.0) (0.6.1)
Requirement already satisfied: ecos>=2 in c:\programdata\anaconda3\lib\site-packages (from cvxpy<2.0.0,>=1.1.10->PyPortfolioOpt==1.4.0) (2.0.7.post1)
Requirement already satisfied: future in c:\programdata\anaconda3\lib\site-packages (from osqp>=0.4.1->cvxpy<2.0.0,>=1.1.10->PyPortfolioOpt==1.4.0) (0.18.2)
Requirement already satisfied: python-dateutil>=2.7.3 in c:\programdata\anaconda3\lib\site-packages (from pandas>=0.19->PyPortfolioOpt==1.4.0) (2.8.1)
Requirement already satisfied: pytz>=2017.3 in c:\programdata\anaconda3\lib\site-packages (from pandas>=0.19->PyPortfolioOpt==1.4.0) (2021.1)
Requirement already satisfied: six>=1.5 in c:\programdata\anaconda3\lib\site-packages (from python-dateutil>=2.7.3->pandas>=0.19->PyPortfolioOpt==1.4.0) (1.15.0)
Building wheels for collected packages: cvxopt
  Building wheel for cvxopt (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: 'C:\ProgramData\Anaconda3\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Admin\\AppData\\Local\\Temp\\pip-install-qhqvz8ye\\cvxopt_9c738ec7a82d4b57a290250a7634947c\\setup.py'"'"'; __file__='"'"'C:\\Users\\Admin\\AppData\\Local\\Temp\\pip-install-qhqvz8ye\\cvxopt_9c738ec7a82d4b57a290250a7634947c\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\Admin\AppData\Local\Temp\pip-wheel-7sc0cbj4'
       cwd: C:\Users\Admin\AppData\Local\Temp\pip-install-qhqvz8ye\cvxopt_9c738ec7a82d4b57a290250a7634947c\
  Complete output (33 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-3.8
  creating build\lib.win-amd64-3.8\cvxopt
  copying src\python\coneprog.py -> build\lib.win-amd64-3.8\cvxopt
  copying src\python\cvxprog.py -> build\lib.win-amd64-3.8\cvxopt
  copying src\python\info.py -> build\lib.win-amd64-3.8\cvxopt
  copying src\python\misc.py -> build\lib.win-amd64-3.8\cvxopt
  copying src\python\modeling.py -> build\lib.win-amd64-3.8\cvxopt
  copying src\python\msk.py -> build\lib.win-amd64-3.8\cvxopt
  copying src\python\printing.py -> build\lib.win-amd64-3.8\cvxopt
  copying src\python\solvers.py -> build\lib.win-amd64-3.8\cvxopt
  copying src\python\_version.py -> build\lib.win-amd64-3.8\cvxopt
  copying src\python\__init__.py -> build\lib.win-amd64-3.8\cvxopt
  UPDATING build\lib.win-amd64-3.8\cvxopt/_version.py
  set build\lib.win-amd64-3.8\cvxopt/_version.py to '1.2.5'
  running build_ext
  building 'base' extension
  creating build\temp.win-amd64-3.8
  creating build\temp.win-amd64-3.8\Release
  creating build\temp.win-amd64-3.8\Release\src
  creating build\temp.win-amd64-3.8\Release\src\c
  C:\ProgramData\Anaconda3\Library\mingw-w64\bin\gcc.exe -mdll -O -Wall -DMS_WIN64 -IC:\ProgramData\Anaconda3\include -IC:\ProgramData\Anaconda3\include -c src/C/base.c -o build\temp.win-amd64-3.8\Release\src\c\base.o
  C:\ProgramData\Anaconda3\Library\mingw-w64\bin\gcc.exe -mdll -O -Wall -DMS_WIN64 -IC:\ProgramData\Anaconda3\include -IC:\ProgramData\Anaconda3\include -c src/C/dense.c -o build\temp.win-amd64-3.8\Release\src\c\dense.o
  C:\ProgramData\Anaconda3\Library\mingw-w64\bin\gcc.exe -mdll -O -Wall -DMS_WIN64 -IC:\ProgramData\Anaconda3\include -IC:\ProgramData\Anaconda3\include -c src/C/sparse.c -o build\temp.win-amd64-3.8\Release\src\c\sparse.o
  writing build\temp.win-amd64-3.8\Release\src\c\base.cp38-win_amd64.def
  C:\ProgramData\Anaconda3\Library\mingw-w64\bin\gcc.exe -shared -s build\temp.win-amd64-3.8\Release\src\c\base.o build\temp.win-amd64-3.8\Release\src\c\dense.o build\temp.win-amd64-3.8\Release\src\c\sparse.o build\temp.win-amd64-3.8\Release\src\c\base.cp38-win_amd64.def -L/usr/lib -LC:\ProgramData\Anaconda3\libs -LC:\ProgramData\Anaconda3\PCbuild\amd64 -lm -llapack -lblas -lpython38 -lmsvcr140 -o build\lib.win-amd64-3.8\cvxopt\base.cp38-win_amd64.pyd
  C:/ProgramData/Anaconda3/Library/mingw-w64/bin/../lib/gcc/x86_64-w64-mingw32/5.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -llapack
  C:/ProgramData/Anaconda3/Library/mingw-w64/bin/../lib/gcc/x86_64-w64-mingw32/5.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lblas
  collect2.exe: error: ld returned 1 exit status
  error: command 'C:\\ProgramData\\Anaconda3\\Library\\mingw-w64\\bin\\gcc.exe' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for cvxopt
  Running setup.py clean for cvxopt
Failed to build cvxopt
Installing collected packages: cvxopt, PyPortfolioOpt
  Attempting uninstall: cvxopt
    Found existing installation: cvxopt 1.2.5.post1
    Uninstalling cvxopt-1.2.5.post1:
      Successfully uninstalled cvxopt-1.2.5.post1
    Running setup.py install for cvxopt ... error
    ERROR: Command errored out with exit status 1:
     command: 'C:\ProgramData\Anaconda3\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Admin\\AppData\\Local\\Temp\\pip-install-qhqvz8ye\\cvxopt_9c738ec7a82d4b57a290250a7634947c\\setup.py'"'"'; __file__='"'"'C:\\Users\\Admin\\AppData\\Local\\Temp\\pip-install-qhqvz8ye\\cvxopt_9c738ec7a82d4b57a290250a7634947c\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\Admin\AppData\Local\Temp\pip-record-dyam3f9y\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\ProgramData\Anaconda3\Include\cvxopt'
         cwd: C:\Users\Admin\AppData\Local\Temp\pip-install-qhqvz8ye\cvxopt_9c738ec7a82d4b57a290250a7634947c\
    Complete output (33 lines):
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.8
    creating build\lib.win-amd64-3.8\cvxopt
    copying src\python\coneprog.py -> build\lib.win-amd64-3.8\cvxopt
    copying src\python\cvxprog.py -> build\lib.win-amd64-3.8\cvxopt
    copying src\python\info.py -> build\lib.win-amd64-3.8\cvxopt
    copying src\python\misc.py -> build\lib.win-amd64-3.8\cvxopt
    copying src\python\modeling.py -> build\lib.win-amd64-3.8\cvxopt
    copying src\python\msk.py -> build\lib.win-amd64-3.8\cvxopt
    copying src\python\printing.py -> build\lib.win-amd64-3.8\cvxopt
    copying src\python\solvers.py -> build\lib.win-amd64-3.8\cvxopt
    copying src\python\_version.py -> build\lib.win-amd64-3.8\cvxopt
    copying src\python\__init__.py -> build\lib.win-amd64-3.8\cvxopt
    UPDATING build\lib.win-amd64-3.8\cvxopt/_version.py
    set build\lib.win-amd64-3.8\cvxopt/_version.py to '1.2.5'
    running build_ext
    building 'base' extension
    creating build\temp.win-amd64-3.8
    creating build\temp.win-amd64-3.8\Release
    creating build\temp.win-amd64-3.8\Release\src
    creating build\temp.win-amd64-3.8\Release\src\c
    C:\ProgramData\Anaconda3\Library\mingw-w64\bin\gcc.exe -mdll -O -Wall -DMS_WIN64 -IC:\ProgramData\Anaconda3\include -IC:\ProgramData\Anaconda3\include -c src/C/base.c -o build\temp.win-amd64-3.8\Release\src\c\base.o
    C:\ProgramData\Anaconda3\Library\mingw-w64\bin\gcc.exe -mdll -O -Wall -DMS_WIN64 -IC:\ProgramData\Anaconda3\include -IC:\ProgramData\Anaconda3\include -c src/C/dense.c -o build\temp.win-amd64-3.8\Release\src\c\dense.o
    C:\ProgramData\Anaconda3\Library\mingw-w64\bin\gcc.exe -mdll -O -Wall -DMS_WIN64 -IC:\ProgramData\Anaconda3\include -IC:\ProgramData\Anaconda3\include -c src/C/sparse.c -o build\temp.win-amd64-3.8\Release\src\c\sparse.o
    writing build\temp.win-amd64-3.8\Release\src\c\base.cp38-win_amd64.def
    C:\ProgramData\Anaconda3\Library\mingw-w64\bin\gcc.exe -shared -s build\temp.win-amd64-3.8\Release\src\c\base.o build\temp.win-amd64-3.8\Release\src\c\dense.o build\temp.win-amd64-3.8\Release\src\c\sparse.o build\temp.win-amd64-3.8\Release\src\c\base.cp38-win_amd64.def -L/usr/lib -LC:\ProgramData\Anaconda3\libs -LC:\ProgramData\Anaconda3\PCbuild\amd64 -lm -llapack -lblas -lpython38 -lmsvcr140 -o build\lib.win-amd64-3.8\cvxopt\base.cp38-win_amd64.pyd
    C:/ProgramData/Anaconda3/Library/mingw-w64/bin/../lib/gcc/x86_64-w64-mingw32/5.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -llapack
    C:/ProgramData/Anaconda3/Library/mingw-w64/bin/../lib/gcc/x86_64-w64-mingw32/5.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lblas
    collect2.exe: error: ld returned 1 exit status
    error: command 'C:\\ProgramData\\Anaconda3\\Library\\mingw-w64\\bin\\gcc.exe' failed with exit status 1
    ----------------------------------------
  Rolling back uninstall of cvxopt
  Moving to c:\programdata\anaconda3\lib\site-packages\cvxopt-1.2.5.post1.dist-info\
   from C:\ProgramData\Anaconda3\Lib\site-packages\~-xopt-1.2.5.post1.dist-info
  Moving to c:\programdata\anaconda3\lib\site-packages\cvxopt\
   from C:\ProgramData\Anaconda3\Lib\site-packages\~vxopt
ERROR: Command errored out with exit status 1: 'C:\ProgramData\Anaconda3\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Admin\\AppData\\Local\\Temp\\pip-install-qhqvz8ye\\cvxopt_9c738ec7a82d4b57a290250a7634947c\\setup.py'"'"'; __file__='"'"'C:\\Users\\Admin\\AppData\\Local\\Temp\\pip-install-qhqvz8ye\\cvxopt_9c738ec7a82d4b57a290250a7634947c\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\Admin\AppData\Local\Temp\pip-record-dyam3f9y\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\ProgramData\Anaconda3\Include\cvxopt' Check the logs for full command output.
```

**Comment by sabirjana** [comment]
Please close this issue, finally, it worked by uninstalling the previous version and then installing the newer version.
Thanks
Sabir
