### ISSUE TITLE
OSError: [WinError 126] The specified module could not be found

### ISSUE THREAD

**Issue by jmaramot08** [robertmartin8/PyPortfolioOpt#311]
Receiving the subject OSError when trying to import the modules. The installation appeared to have no issues as running the standard pip install PyPortfolioOpt shows v1.4.1 successfully installed.

See below for complete Traceback:

```
Traceback (most recent call last):
  File "c:*/optimized.py", line 10, in <module>
    from pypfopt import EfficientFrontier
  File "C:*\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\pypfopt\__init__.py", line 1, in <module>
    from .black_litterman import (
  File "C:*\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\pypfopt\black_litterman.py", line 13, in <module>
    from . import base_optimizer
  File "C:*\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\pypfopt\base_optimizer.py", line 14, in <module>
    import cvxpy as cp
  File "C:*\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\cvxpy\__init__.py", line 18, in <module>
    from cvxpy.atoms import *
  File "C:*\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\cvxpy\atoms\__init__.py", line 17, in <module>
    from cvxpy.atoms.cummax import cummax
  File "C:*\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\cvxpy\atoms\cummax.py", line 17, in <module>
    from cvxpy.atoms.atom import Atom
  File "C:*\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\cvxpy\atoms\atom.py", line 18, in <module>
    from cvxpy import utilities as u
  File "C:*\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\cvxpy\utilities\__init__.py", line 18, in <module>
    from . import grad
  File "C:*\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\cvxpy\utilities\grad.py", line 19, in <module>
    import scipy.sparse as sp
  File "C:*\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\scipy\__init__.py", line 130, in <module>
    from . import _distributor_init
  File "C:*\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\scipy\_distributor_init.py", line 61, in <module>
    WinDLL(os.path.abspath(filename))
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.2544.0_x64__qbz5n2kfra8p0\lib\ctypes\__init__.py", 
line 364, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 126] The specified module could not be found
```

**Comment by robertmartin8** [comment]
@jmaramot08 can you check that CVXPY has been installed? e.g by opening a python shell and running `import cvxpy`

**Comment by jmaramot08** [comment]
@robertmartin8 I apologize, I'm using Windows 10 and Python v3.7.9.

So, I got a similar error when running `import cvxpy` in a Python shell. Ran `pip install cvxpy`, and it appears I already had it installed, v1.1.11.

**Comment by robertmartin8** [comment]
@jmaramot08 

That's very strange, does it occur for other packages too? 

I had a quick google, and it seems that this is a windows-specific issue (search `OSError: [WinError 126] The specified module could not be found`). Perhaps one of those threads will have an answer for you? I'm not very familiar with windows so can't be of much help unfortunately

**Comment by robertmartin8** [comment]
I'm closing this for now, as it's unclear if it's a PyPortfolioOpt issue. Please reopen if there are updates
