### ISSUE TITLE
Error trying to import EfficientFrontier

### ISSUE THREAD

**Issue by OscarLazcano** [robertmartin8/PyPortfolioOpt#322]
I am having some error importing EfficentFrontier. I think I properly installed the module, i.e  downloaded C++ and followed the instructions. However, I am still getting this error:

```
 from pypfopt.efficient_frontier import EfficientFrontier

Traceback (most recent call last):
  File "C:\Users\Oscar 2\AppData\Local\Programs\Python\Python38\lib\site-packages\IPython\core\interactiveshell.py", line 3418, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-3-8888af095db4>", line 1, in <module>
    from pypfopt.efficient_frontier import EfficientFrontier
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2020.2.2\plugins\python-ce\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "C:\Users\Oscar 2\AppData\Local\Programs\Python\Python38\lib\site-packages\pypfopt\__init__.py", line 1, in <module>
    from .black_litterman import (
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2020.2.2\plugins\python-ce\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "C:\Users\Oscar 2\AppData\Local\Programs\Python\Python38\lib\site-packages\pypfopt\black_litterman.py", line 13, in <module>
    from . import base_optimizer
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2020.2.2\plugins\python-ce\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "C:\Users\Oscar 2\AppData\Local\Programs\Python\Python38\lib\site-packages\pypfopt\base_optimizer.py", line 14, in <module>
    import cvxpy as cp
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2020.2.2\plugins\python-ce\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "C:\Users\Oscar 2\AppData\Local\Programs\Python\Python38\lib\site-packages\cvxpy\__init__.py", line 18, in <module>
    from cvxpy.atoms import *
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2020.2.2\plugins\python-ce\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "C:\Users\Oscar 2\AppData\Local\Programs\Python\Python38\lib\site-packages\cvxpy\atoms\__init__.py", line 20, in <module>
    from cvxpy.atoms.geo_mean import geo_mean
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2020.2.2\plugins\python-ce\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "C:\Users\Oscar 2\AppData\Local\Programs\Python\Python38\lib\site-packages\cvxpy\atoms\geo_mean.py", line 20, in <module>
    from cvxpy.utilities.power_tools import (fracify, decompose, approx_error, lower_bound,
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2020.2.2\plugins\python-ce\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "C:\Users\Oscar 2\AppData\Local\Programs\Python\Python38\lib\site-packages\cvxpy\utilities\power_tools.py", line 18, in <module>
    from cvxpy.atoms.affine.reshape import reshape
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2020.2.2\plugins\python-ce\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "C:\Users\Oscar 2\AppData\Local\Programs\Python\Python38\lib\site-packages\cvxpy\atoms\affine\reshape.py", line 18, in <module>
    from cvxpy.atoms.affine.hstack import hstack
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2020.2.2\plugins\python-ce\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "C:\Users\Oscar 2\AppData\Local\Programs\Python\Python38\lib\site-packages\cvxpy\atoms\affine\hstack.py", line 18, in <module>
    from cvxpy.atoms.affine.affine_atom import AffAtom
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2020.2.2\plugins\python-ce\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "C:\Users\Oscar 2\AppData\Local\Programs\Python\Python38\lib\site-packages\cvxpy\atoms\affine\affine_atom.py", line 22, in <module>
    from cvxpy.cvxcore.python import canonInterface
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2020.2.2\plugins\python-ce\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "C:\Users\Oscar 2\AppData\Local\Programs\Python\Python38\lib\site-packages\cvxpy\cvxcore\python\__init__.py", line 3, in <module>
    import _cvxcore
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2020.2.2\plugins\python-ce\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
ImportError: numpy.core.multiarray failed to import
```

As suggested in some posts, I installed cvxpy and i didn't have any issue. It seems to be something realted with numpy.

thanks

**Comment by robertmartin8** [comment]
Hi @OscarLazcano,

In situations like this it's useful to isolate which package is causing the installation issues. Are you able to `import numpy` on its own?

**Comment by OscarLazcano** [comment]
Thank you for the tip. Uninstalled numpy and worked perfectly. I guess it was a beginners mistakes. Thanks for the prompt answer

**Comment by robertmartin8** [comment]
No worries. Glad you got it to work!

**Comment by ibaris** [comment]
I don´t think that uninstalling `numpy` should be the right solution. This seems to be an issue related to version incompatibilities between `CVXPY` and `numpy`, as you can see [here](https://github.com/cvxpy/cvxpy/issues/1229).  If you update you `numpy` distribution this issue should be solved:

```console
> pip install numpy --upgrade 
```
