### ISSUE TITLE
I cant't install PyPortfolioOpt on the Python Env to use PBI

### ISSUE THREAD

**Issue by klemeragm** [robertmartin8/PyPortfolioOpt#368]
Hi, I have been used PBI to create Dashboards and analysis and I cant import the pyportfolio to PBI

Anyone have some solution to put the library in PBI? I would like to put my solutions in the Dashboard. 

Script Anaconda Prompt:

```
(base) C:\Users\Klemer>conda activate envpowerbi

(envpowerbi) C:\Users\Klemer>pip install PyPortfolioOpt
Traceback (most recent call last):
  File "C:\Users\Klemer\anaconda3\envs\envpowerbi\Scripts\pip-script.py", line 6, in <module>
    from pip._internal.cli.main import main
  File "C:\Users\Klemer\anaconda3\envs\envpowerbi\lib\site-packages\pip\_internal\cli\main.py", line 8, in <module>
    from pip._internal.cli.autocompletion import autocomplete
  File "C:\Users\Klemer\anaconda3\envs\envpowerbi\lib\site-packages\pip\_internal\cli\autocompletion.py", line 9, in <module>
    from pip._internal.cli.main_parser import create_main_parser
  File "C:\Users\Klemer\anaconda3\envs\envpowerbi\lib\site-packages\pip\_internal\cli\main_parser.py", line 7, in <module>
    from pip._internal.cli import cmdoptions
  File "C:\Users\Klemer\anaconda3\envs\envpowerbi\lib\site-packages\pip\_internal\cli\cmdoptions.py", line 22, in <module>
    from pip._internal.cli.progress_bars import BAR_TYPES
  File "C:\Users\Klemer\anaconda3\envs\envpowerbi\lib\site-packages\pip\_internal\cli\progress_bars.py", line 9, in <module>
    from pip._internal.utils.logging import get_indentation
  File "C:\Users\Klemer\anaconda3\envs\envpowerbi\lib\site-packages\pip\_internal\utils\logging.py", line 14, in <module>
    from pip._internal.utils.misc import ensure_dir
  File "C:\Users\Klemer\anaconda3\envs\envpowerbi\lib\site-packages\pip\_internal\utils\misc.py", line 29, in <module>
    from pip._internal.locations import get_major_minor_version, site_packages, user_site
  File "C:\Users\Klemer\anaconda3\envs\envpowerbi\lib\site-packages\pip\_internal\locations\__init__.py", line 14, in <module>
    from . import _distutils, _sysconfig
  File "C:\Users\Klemer\anaconda3\envs\envpowerbi\lib\site-packages\pip\_internal\locations\_sysconfig.py", line 8, in <module>
    from pip._internal.exceptions import InvalidSchemeCombination, UserInstallationInvalid
ImportError: cannot import name 'InvalidSchemeCombination'

```

**Comment by robertmartin8** [comment]
Hi @klemeragm,

Do you have this issue with any other libraries? e.g if you try `pip install cvxpy`. I have no experience with PBI so probably won't be able to help with this one.

Best,
Robert

**Comment by phschiele** [comment]
@klemeragm Which pip version are you using?

**Comment by robertmartin8** [comment]
Closing because stale – feel free to reopen if needed
