### ISSUE TITLE
osqp-0.6.2.post5.tar.gz >> subprocess exited with error

### ISSUE THREAD

**Issue by akhil30garg** [robertmartin8/PyPortfolioOpt#430]
```
Using cached osqp-0.6.2.post5.tar.gz (226 kB)
  Installing build dependencies ... error
  error: subprocess-exited-with-error

  × pip subprocess to install build dependencies did not run successfully.
  │ exit code: 1
  ╰─> [95 lines of output]
      Collecting oldest-supported-numpy
        Using cached oldest_supported_numpy-2022.1.30-py3-none-any.whl (3.9 kB)
      Collecting setuptools>=40.8.0
        Using cached setuptools-61.1.1-py3-none-any.whl (1.1 MB)
      Collecting wheel
        Using cached wheel-0.37.1-py2.py3-none-any.whl (35 kB)
      Collecting setuptools_scm>=6.2
        Using cached setuptools_scm-6.4.2-py3-none-any.whl (37 kB)
      Collecting qdldl
        Using cached qdldl-0.1.5.post0.tar.gz (69 kB)
        Preparing metadata (setup.py): started
        Preparing metadata (setup.py): finished with status 'done'
      Collecting numpy==1.17.3
        Using cached numpy-1.17.3-cp38-cp38-win32.whl (10.8 MB)
      Collecting packaging>=20.0
        Using cached packaging-21.3-py3-none-any.whl (40 kB)
      Collecting tomli>=1.0.0
        Using cached tomli-2.0.1-py3-none-any.whl (12 kB)
      Collecting scipy>=0.13.2
        Using cached scipy-1.8.0-cp38-cp38-win32.whl (33.4 MB)
      Collecting pyparsing!=3.0.5,>=2.0.2
        Using cached pyparsing-3.0.7-py3-none-any.whl (98 kB)
      Using legacy 'setup.py install' for qdldl, since package 'wheel' is not installed.
      Installing collected packages: wheel, tomli, setuptools, pyparsing, numpy, scipy, packaging, oldest-supported-numpy, setuptools_scm, qdldl
        Running setup.py install for qdldl: started
        Running setup.py install for qdldl: finished with status 'error'
        error: subprocess-exited-with-error

        Running setup.py install for qdldl did not run successfully.
        exit code: 1

        [52 lines of output]
        running install
        running build
        running build_ext
        Traceback (most recent call last):
          File "C:\Users\akhil\AppData\Local\Temp\pip-install-l9yeyjte\qdldl_0074b278521046c8a6d3584596fd45cb\setup.py", line 78, in build_extensions
            check_output(['cmake', '--version'])
          File "c:\python\python38-32\lib\subprocess.py", line 411, in check_output
            return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
          File "c:\python\python38-32\lib\subprocess.py", line 489, in run
            with Popen(*popenargs, **kwargs) as process:
          File "c:\python\python38-32\lib\subprocess.py", line 854, in __init__
            self._execute_child(args, executable, preexec_fn, close_fds,
          File "c:\python\python38-32\lib\subprocess.py", line 1307, in _execute_child
            hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
        FileNotFoundError: [WinError 2] The system cannot find the file specified

        During handling of the above exception, another exception occurred:

        Traceback (most recent call last):
          File "<string>", line 2, in <module>
          File "<pip-setuptools-caller>", line 34, in <module>
          File "C:\Users\akhil\AppData\Local\Temp\pip-install-l9yeyjte\qdldl_0074b278521046c8a6d3584596fd45cb\setup.py", line 110, in <module>
            setup(name='qdldl',
          File "c:\python\python38-32\lib\site-packages\setuptools\__init__.py", line 145, in setup
            return distutils.core.setup(**attrs)
          File "c:\python\python38-32\lib\distutils\core.py", line 148, in setup
            dist.run_commands()
          File "c:\python\python38-32\lib\distutils\dist.py", line 966, in run_commands
            self.run_command(cmd)
          File "c:\python\python38-32\lib\distutils\dist.py", line 985, in run_command
            cmd_obj.run()
          File "c:\python\python38-32\lib\site-packages\setuptools\command\install.py", line 61, in run
            return orig.install.run(self)
          File "c:\python\python38-32\lib\distutils\command\install.py", line 545, in run
            self.run_command('build')
          File "c:\python\python38-32\lib\distutils\cmd.py", line 313, in run_command
            self.distribution.run_command(command)
          File "c:\python\python38-32\lib\distutils\dist.py", line 985, in run_command
            cmd_obj.run()
          File "c:\python\python38-32\lib\distutils\command\build.py", line 135, in run
            self.run_command(cmd_name)
          File "c:\python\python38-32\lib\distutils\cmd.py", line 313, in run_command
            self.distribution.run_command(command)
          File "c:\python\python38-32\lib\distutils\dist.py", line 985, in run_command
            cmd_obj.run()
          File "c:\python\python38-32\lib\site-packages\setuptools\command\build_ext.py", line 84, in run
            _build_ext.run(self)
          File "c:\python\python38-32\lib\distutils\command\build_ext.py", line 340, in run
            self.build_extensions()
          File "C:\Users\akhil\AppData\Local\Temp\pip-install-l9yeyjte\qdldl_0074b278521046c8a6d3584596fd45cb\setup.py", line 80, in build_extensions
            raise RuntimeError("CMake must be installed to build qdldl")
        RuntimeError: CMake must be installed to build qdldl
        [end of output]

        note: This error originates from a subprocess, and is likely not a problem with pip.
      error: legacy-install-failure

      Encountered error while trying to install package.

      qdldl

      note: This is an issue with the package mentioned above, not pip.
      hint: See above for output from the failure.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× pip subprocess to install build dependencies did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

**Comment by robertmartin8** [comment]
Have you followed the windows installs [instructions](https://pyportfolioopt.readthedocs.io/en/latest/index.html#installation)?

**Comment by robertmartin8** [comment]
Closing due to inactivity
