### ISSUE TITLE
Plotting issues

### ISSUE THREAD

**Issue by acastiel** [robertmartin8/PyPortfolioOpt#433]
It seems the Plotting module is not working properly:

using

from pypfopt import plotting 
ef = pf.EfficientFrontier(mu, S)
plotting.plot_efficient_frontier(ef,ax=ax)

I have this message: TypeError: cannot pickle 'osqp.OSQP_results' object

**Comment by robertmartin8** [comment]
I can't reproduce this: it works for me

**Comment by yosukesan** [comment]
I had the same issue on my host. Seeking way around by using docker now, but still unsuccessful either.
Is this reproducible for you ? I also found pytest failed in my host env. Please check my following report after this.

* env
  - debian 11
  - python3.9  3.9.2-1
  - pyportfolioopt 1.5.3

* Input
```
import pandas as pd
import matplotlib.pyplot as plt
from pypfopt import EfficientFrontier
from pypfopt import risk_models
from pypfopt import expected_returns
from pypfopt import plotting
import copy

# Read in price data
df = pd.read_csv("PyPortfolioOpt/tests/resources/stock_prices.csv", parse_dates=True, index_col="date")

# Calculate expected returns and sample covariance
mu = expected_returns.mean_historical_return(df)
S = risk_models.sample_cov(df)

# Optimize for maximal Sharpe ratio
ef = EfficientFrontier(mu, S)
raw_weights = ef.max_sharpe()
cleaned_weights = ef.clean_weights()
ef.save_weights_to_file("weights.csv")  # saves to file
print(cleaned_weights)
ef.portfolio_performance(verbose=True)

fig, ax = plt.subplots()
plotting.plot_efficient_frontier(ef, ax=ax, show_assets=True)
```

* Err log
```
python efficent_front_plot_sample.py 
OrderedDict([('GOOG', 0.03835), ('AAPL', 0.0689), ('FB', 0.20603), ('BABA', 0.07315), ('AMZN', 0.04033), ('GE', 0.0), ('AMD', 0.0), ('WMT', 0.0), ('BAC', 0.0), ('GM', 0.0), ('T', 0.0), ('UAA', 0.0), ('SHLD', 0.0), ('XOM', 0.0), ('RRC', 0.0), ('BBY', 0.01324), ('MA', 0.35349), ('PFE', 0.1957), ('JPM', 0.0), ('SBUX', 0.01082)])
Expected annual return: 30.5%
Annual volatility: 22.2%
Sharpe Ratio: 1.28
Traceback (most recent call last):
  File "/home/yosuke/Data/finance/py_portfolio_opt/PyPortfolioOpt/efficent_front_plot_sample.py", line 26, in <module>
    plotting.plot_efficient_frontier(ef, ax=ax, show_assets=True)
  File "/home/yosuke/.local/lib/python3.9/site-packages/pypfopt/plotting.py", line 261, in plot_efficient_frontier
    ef_param_range = _ef_default_returns_range(opt, points)
  File "/home/yosuke/.local/lib/python3.9/site-packages/pypfopt/plotting.py", line 159, in _ef_default_returns_range
    ef_minvol = copy.deepcopy(ef)
  File "/usr/lib/python3.9/copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/usr/lib/python3.9/copy.py", line 270, in _reconstruct
    state = deepcopy(state, memo)
  File "/usr/lib/python3.9/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python3.9/copy.py", line 230, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib/python3.9/copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/usr/lib/python3.9/copy.py", line 270, in _reconstruct
    state = deepcopy(state, memo)
  File "/usr/lib/python3.9/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python3.9/copy.py", line 230, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib/python3.9/copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/usr/lib/python3.9/copy.py", line 270, in _reconstruct
    state = deepcopy(state, memo)
  File "/usr/lib/python3.9/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python3.9/copy.py", line 230, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib/python3.9/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python3.9/copy.py", line 230, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib/python3.9/copy.py", line 161, in deepcopy
    rv = reductor(4)
TypeError: cannot pickle 'osqp.OSQP_results' object
```

**Comment by robertmartin8** [comment]
In your second last comment, the error _is_ reproducible to me but also there's a problem with the code:

One shouldn't call any optimisation method on the `EfficientFrontier` object before running the plotting function. So when I changed it to the below, it worked:

```python
import pandas as pd
import matplotlib.pyplot as plt
from pypfopt import EfficientFrontier
from pypfopt import risk_models
from pypfopt import expected_returns
from pypfopt import plotting
import copy

# Read in price data
df = pd.read_csv("PyPortfolioOpt/tests/resources/stock_prices.csv", parse_dates=True, index_col="date")

# Calculate expected returns and sample covariance
mu = expected_returns.mean_historical_return(df)
S = risk_models.sample_cov(df)

# Optimize for maximal Sharpe ratio
ef = EfficientFrontier(mu, S)

# COMMENTING OUT BELOW
# raw_weights = ef.max_sharpe()
# cleaned_weights = ef.clean_weights()
# ef.save_weights_to_file("weights.csv")  # saves to file
# print(cleaned_weights)
# ef.portfolio_performance(verbose=True)

fig, ax = plt.subplots()
plotting.plot_efficient_frontier(ef, ax=ax, show_assets=True)
```

As for the testing issues you pointed out, these are indeed valid and I have observed them from time to time. I think it is a result of different plotting backends creating slightly different objects when plotting. So I will modify the tests slightly. Thanks for pointing this out!

**Comment by yosukesan** [comment]
Worked on my env. Thanks !

![issue_433_plotting_issue](https://user-images.githubusercontent.com/11629705/204957644-f34be160-7a13-4390-a0b6-36dfc9c76496.png)

Just added plt.show() for completeness.
```
import pandas as pd
import matplotlib.pyplot as plt
from pypfopt import EfficientFrontier
from pypfopt import risk_models
from pypfopt import expected_returns
from pypfopt import plotting
import copy

# Read in price data
df = pd.read_csv("PyPortfolioOpt/tests/resources/stock_prices.csv", parse_dates=True, index_col="date")

# Calculate expected returns and sample covariance
mu = expected_returns.mean_historical_return(df)
S = risk_models.sample_cov(df)

# Optimize for maximal Sharpe ratio
ef = EfficientFrontier(mu, S)

# COMMENTING OUT BELOW
# raw_weights = ef.max_sharpe()
# cleaned_weights = ef.clean_weights()
# ef.save_weights_to_file("weights.csv")  # saves to file
# print(cleaned_weights)
# ef.portfolio_performance(verbose=True)

fig, ax = plt.subplots()
plotting.plot_efficient_frontier(ef, ax=ax, show_assets=True)
plt.show()
```
