### ISSUE TITLE
ModuleNotFoundError

### ISSUE THREAD

**Issue by heartwxmddd** [robertmartin8/PyPortfolioOpt#462]
**********Describe the bug**********
Traceback (most recent call last):
  File "G:/量化研究/youmy/量化配置/BL.py", line 44, in <module>
    from pypfopt import black_litterman, risk_models
  File "D:\Python\lib\site-packages\pyportfolioopt-1.5.1-py3.7.egg\pypfopt\__init__.py", line 8, in <module>
ModuleNotFoundError: No module named 'pypfopt.efficient_frontier'
 **************
Hi

i am trying to use the B-L moudel in [PyPortfolioOpt]

I download it from github and setup on my PC in local environment.

And i am sure pyportfolioopt-1.5.1-py3.7.egg is in the path D:\Python\lib\site-packages now.
i also rename the filename from  PyPortfolioOpt into pyportfolioopt 
but it still report this error , how should i fix this problem?

Many thanks

**Comment by heartwxmddd** [comment]
fixed
