### ISSUE TITLE
unable to install the package

### ISSUE THREAD

**Issue by antoinew209** [robertmartin8/PyPortfolioOpt#91]
Hi,
I have used pip install command on the windows command line and the below is what I am getting as error message.
Can you please help me?
Thank you in advance,
Best,
Antoine
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
  ERROR: Command errored out with exit status 1:
     command: 'C:\Users\antoi\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\antoi\\AppData\\Local\\Temp\\pip-install-pmsfv37p\\osqp\\setup.py'"'"'; __file__='"'"'C:\\Users\\antoi\\AppData\\Local\\Temp\\pip-install-pmsfv37p\\osqp\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\antoi\AppData\Local\Temp\pip-install-pmsfv37p\osqp\pip-egg-info'
         cwd: C:\Users\antoi\AppData\Local\Temp\pip-install-pmsfv37p\osqp\
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\antoi\AppData\Local\Temp\pip-install-pmsfv37p\osqp\setup.py", line 11, in <module>
        import numpy
    ModuleNotFoundError: No module named 'numpy'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by robertmartin8** [comment]
Hi @antoinew209,

Could you let me know what happens when you try `pip install numpy` then `pip install pyportfolioopt`? 

Robert

**Comment by antoinew209** [comment]
Hi @robertmartin8,

Thank you so much for coming back to me so quick!

I think I made some steps forward but I still can't use the project. I am attaching the results of both queries: [pip install PyPortfolioOpt.txt](https://github.com/robertmartin8/PyPortfolioOpt/files/4496832/pip.install.PyPortfolioOpt.txt) and [python setup.py install.txt](https://github.com/robertmartin8/PyPortfolioOpt/files/4496833/python.setup.py.install.txt). I am wondering if I didn't actually succeed installing it (to be honest, I have never used that environment before... I usually only use Excel!). 

I tried to open the file "pyportfolioopt-1.1.0-py3.8.egg" from Panda Viewer but all I see is a grey screen and the following text: [Panda Viewer LOG.txt](https://github.com/robertmartin8/PyPortfolioOpt/files/4496840/Panda.Viewer.LOG.txt)

Hopefully, it is just a python-noob error this time... I already spent a lot of time to get to that point ^^.

Thank you again,
Best regards,

Antoine

**Comment by robertmartin8** [comment]
@antoinew209 

1. Try opening a new terminal and running `pip install numpy`. You can verify that it is installed by typing `python` into the terminal, then when the python shell opens, `import numpy`. If there are no errors, exit the shell (ctrl D) 
2. Run `pip install pyportfolioopt`. If there aren't any errors, you should be able to open the shell and type `import pypfopt`.

**Comment by antoinew209** [comment]
@robertmartin8 Hi again, I managed to make step 1 in a windows terminal window ; step 2 failed since  I am missing cvxpy (and I can't find a way to resolve that issue). 
What is interesting is that I also managed to make step 1 AND 2 in a Anaconda window... However, after I type import pypfopt and press enter, nothing happens and the cursor goes to next line, like this:
>>> import pypfopt
>>>
I hope you can help me further. Thank you again!

**Comment by robertmartin8** [comment]
@antoinew209 

Did you `pip install cvxpy` for the former case? 

For anaconda, when you typed `import pypfopt`, did you do it from within a python shell?

**Comment by robertmartin8** [comment]
@antoinew209 

Any updates on this?

**Comment by willytogi** [comment]
Hello Robert, my name is Willy, 

Why there is an error when installing the PyPortfolioOpt:
Collecting PyPortfolioOpt
  Using cached pyportfolioopt-1.5.5-py3-none-any.whl (61 kB)
Collecting cvxpy<2.0.0,>=1.1.19 (from PyPortfolioOpt)
  Using cached cvxpy-1.3.2-cp310-cp310-macosx_10_9_universal2.whl (1.2 MB)
Requirement already satisfied: numpy<2.0.0,>=1.22.4 in ./anaconda3/lib/python3.10/site-packages (from PyPortfolioOpt) (1.25.0)
Requirement already satisfied: pandas>=0.19 in ./anaconda3/lib/python3.10/site-packages (from PyPortfolioOpt) (2.0.3)
Requirement already satisfied: scipy<2.0,>=1.3 in ./anaconda3/lib/python3.10/site-packages (from PyPortfolioOpt) (1.11.1)
Collecting osqp>=0.4.1 (from cvxpy<2.0.0,>=1.1.19->PyPortfolioOpt)
  Using cached osqp-0.6.3.tar.gz (228 kB)
  Installing build dependencies ... error
  error: subprocess-exited-with-error
  
  × pip subprocess to install build dependencies did not run successfully.
  │ exit code: 1
  ╰─> [107 lines of output]
      Collecting oldest-supported-numpy
        Using cached oldest_supported_numpy-2022.11.19-py3-none-any.whl (4.9 kB)
      Collecting setuptools>=40.8.0
        Using cached setuptools-68.0.0-py3-none-any.whl (804 kB)
      Collecting wheel
        Using cached wheel-0.40.0-py3-none-any.whl (64 kB)
      Collecting setuptools_scm>=6.2
        Using cached setuptools_scm-7.1.0-py3-none-any.whl (43 kB)
      Collecting qdldl
        Using cached qdldl-0.1.7.post0.tar.gz (70 kB)
        Installing build dependencies: started
        Installing build dependencies: finished with status 'done'
        Getting requirements to build wheel: started
        Getting requirements to build wheel: finished with status 'done'
        Installing backend dependencies: started
        Installing backend dependencies: finished with status 'done'
        Preparing metadata (pyproject.toml): started
        Preparing metadata (pyproject.toml): finished with status 'done'
      Collecting numpy==1.21.6 (from oldest-supported-numpy)
        Using cached numpy-1.21.6-cp310-cp310-macosx_11_0_arm64.whl (12.4 MB)
      Collecting packaging>=20.0 (from setuptools_scm>=6.2)
        Using cached packaging-23.1-py3-none-any.whl (48 kB)
      Collecting typing-extensions (from setuptools_scm>=6.2)
        Using cached typing_extensions-4.7.1-py3-none-any.whl (33 kB)
      Collecting tomli>=1.0.0 (from setuptools_scm>=6.2)
        Using cached tomli-2.0.1-py3-none-any.whl (12 kB)
      Collecting scipy>=0.13.2 (from qdldl)
        Using cached scipy-1.11.1-cp310-cp310-macosx_12_0_arm64.whl (29.6 MB)
      Building wheels for collected packages: qdldl
        Building wheel for qdldl (pyproject.toml): started
        Building wheel for qdldl (pyproject.toml): finished with status 'error'
        error: subprocess-exited-with-error
      
        × Building wheel for qdldl (pyproject.toml) did not run successfully.
        │ exit code: 1
        ╰─> [65 lines of output]
            running bdist_wheel
            running build
            running build_ext
            Traceback (most recent call last):
              File "<string>", line 81, in build_extensions
              File "/Users/willytogi/anaconda3/lib/python3.10/subprocess.py", line 421, in check_output
                return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
              File "/Users/willytogi/anaconda3/lib/python3.10/subprocess.py", line 503, in run
                with Popen(*popenargs, **kwargs) as process:
              File "/Users/willytogi/anaconda3/lib/python3.10/subprocess.py", line 971, in __init__
                self._execute_child(args, executable, preexec_fn, close_fds,
              File "/Users/willytogi/anaconda3/lib/python3.10/subprocess.py", line 1847, in _execute_child
                raise child_exception_type(errno_num, err_msg, err_filename)
            FileNotFoundError: [Errno 2] No such file or directory: 'cmake'
      
            During handling of the above exception, another exception occurred:
      
            Traceback (most recent call last):
              File "/Users/willytogi/anaconda3/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
                main()
              File "/Users/willytogi/anaconda3/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
                json_out['return_val'] = hook(**hook_input['kwargs'])
              File "/Users/willytogi/anaconda3/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 251, in build_wheel
                return _build_backend().build_wheel(wheel_directory, config_settings,
              File "/private/var/folders/c2/99nlkqh52bg9spdjw2bjjdtr0000gn/T/pip-build-env-cexzdcsq/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 416, in build_wheel
                return self._build_with_temp_dir(['bdist_wheel'], '.whl',
              File "/private/var/folders/c2/99nlkqh52bg9spdjw2bjjdtr0000gn/T/pip-build-env-cexzdcsq/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 401, in _build_with_temp_dir
                self.run_setup()
              File "/private/var/folders/c2/99nlkqh52bg9spdjw2bjjdtr0000gn/T/pip-build-env-cexzdcsq/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 338, in run_setup
                exec(code, locals())
              File "<string>", line 113, in <module>
              File "/private/var/folders/c2/99nlkqh52bg9spdjw2bjjdtr0000gn/T/pip-build-env-cexzdcsq/overlay/lib/python3.10/site-packages/setuptools/__init__.py", line 107, in setup
                return distutils.core.setup(**attrs)
              File "/private/var/folders/c2/99nlkqh52bg9spdjw2bjjdtr0000gn/T/pip-build-env-cexzdcsq/overlay/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 185, in setup
                return run_commands(dist)
              File "/private/var/folders/c2/99nlkqh52bg9spdjw2bjjdtr0000gn/T/pip-build-env-cexzdcsq/overlay/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
                dist.run_commands()
              File "/private/var/folders/c2/99nlkqh52bg9spdjw2bjjdtr0000gn/T/pip-build-env-cexzdcsq/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
                self.run_command(cmd)
              File "/private/var/folders/c2/99nlkqh52bg9spdjw2bjjdtr0000gn/T/pip-build-env-cexzdcsq/overlay/lib/python3.10/site-packages/setuptools/dist.py", line 1234, in run_command
                super().run_command(command)
              File "/private/var/folders/c2/99nlkqh52bg9spdjw2bjjdtr0000gn/T/pip-build-env-cexzdcsq/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
                cmd_obj.run()
              File "/private/var/folders/c2/99nlkqh52bg9spdjw2bjjdtr0000gn/T/pip-build-env-cexzdcsq/normal/lib/python3.10/site-packages/wheel/bdist_wheel.py", line 343, in run
                self.run_command("build")
              File "/private/var/folders/c2/99nlkqh52bg9spdjw2bjjdtr0000gn/T/pip-build-env-cexzdcsq/overlay/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
                self.distribution.run_command(command)
              File "/private/var/folders/c2/99nlkqh52bg9spdjw2bjjdtr0000gn/T/pip-build-env-cexzdcsq/overlay/lib/python3.10/site-packages/setuptools/dist.py", line 1234, in run_command
                super().run_command(command)
              File "/private/var/folders/c2/99nlkqh52bg9spdjw2bjjdtr0000gn/T/pip-build-env-cexzdcsq/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
                cmd_obj.run()
              File "/private/var/folders/c2/99nlkqh52bg9spdjw2bjjdtr0000gn/T/pip-build-env-cexzdcsq/overlay/lib/python3.10/site-packages/setuptools/_distutils/command/build.py", line 131, in run
                self.run_command(cmd_name)
              File "/private/var/folders/c2/99nlkqh52bg9spdjw2bjjdtr0000gn/T/pip-build-env-cexzdcsq/overlay/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
                self.distribution.run_command(command)
              File "/private/var/folders/c2/99nlkqh52bg9spdjw2bjjdtr0000gn/T/pip-build-env-cexzdcsq/overlay/lib/python3.10/site-packages/setuptools/dist.py", line 1234, in run_command
                super().run_command(command)
              File "/private/var/folders/c2/99nlkqh52bg9spdjw2bjjdtr0000gn/T/pip-build-env-cexzdcsq/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
                cmd_obj.run()
              File "/private/var/folders/c2/99nlkqh52bg9spdjw2bjjdtr0000gn/T/pip-build-env-cexzdcsq/overlay/lib/python3.10/site-packages/setuptools/command/build_ext.py", line 84, in run
                _build_ext.run(self)
              File "/private/var/folders/c2/99nlkqh52bg9spdjw2bjjdtr0000gn/T/pip-build-env-cexzdcsq/overlay/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 345, in run
                self.build_extensions()
              File "<string>", line 83, in build_extensions
            RuntimeError: CMake must be installed to build qdldl
            [end of output]
      
        note: This error originates from a subprocess, and is likely not a problem with pip.
        ERROR: Failed building wheel for qdldl
      Failed to build qdldl
      ERROR: Could not build wheels for qdldl, which is required to install pyproject.toml-based projects
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× pip subprocess to install build dependencies did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
